
package jobs.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Tue Apr 09 03:10:28 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "getUserResponse", namespace = "http://org.ws.jobs/soap/service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUserResponse", namespace = "http://org.ws.jobs/soap/service")

public class GetUserResponse {

    @XmlElement(name = "return")
    private jobs.ws.model.User _return;

    public jobs.ws.model.User getReturn() {
        return this._return;
    }

    public void setReturn(jobs.ws.model.User new_return)  {
        this._return = new_return;
    }

}

