
package jobs.ws.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Tue Apr 09 03:10:28 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "updateUser", namespace = "http://org.ws.jobs/soap/service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateUser", namespace = "http://org.ws.jobs/soap/service", propOrder = {"id", "user"})

public class UpdateUser {

    @XmlElement(name = "id")
    private int id;
    @XmlElement(name = "user")
    private jobs.ws.model.User user;

    public int getId() {
        return this.id;
    }

    public void setId(int newId)  {
        this.id = newId;
    }

    public jobs.ws.model.User getUser() {
        return this.user;
    }

    public void setUser(jobs.ws.model.User newUser)  {
        this.user = newUser;
    }

}

