
package jobs.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-09T04:29:07.935+02:00
 * Generated source version: 3.5.7
 *
 */
public final class UserManagementImpl_UserManagementImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://org.ws.jobs/soap/service", "UserManagementImplService");

    private UserManagementImpl_UserManagementImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserManagementImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UserManagementImplService ss = new UserManagementImplService(wsdlURL, SERVICE_NAME);
        UserManagementImpl port = ss.getUserManagementImplPort();

        {
        System.out.println("Invoking addUser...");
        jobs.ws.client.User _addUser_user = new jobs.ws.client.User();
        _addUser_user.setAddress("Address1684790709");
        _addUser_user.setAge(-163393802);
        java.util.List<java.lang.String> _addUser_userCertifications = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addUser_userCertificationsVal1 = "_addUser_userCertificationsVal1188359390";
        _addUser_userCertifications.add(_addUser_userCertificationsVal1);
        _addUser_user.getCertifications().addAll(_addUser_userCertifications);
        _addUser_user.setEducationLevel("EducationLevel241802046");
        _addUser_user.setEmail("Email-286839346");
        _addUser_user.setFirstName("FirstName-1774291862");
        _addUser_user.setId(-134302459);
        java.util.List<java.lang.String> _addUser_userLanguages = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addUser_userLanguagesVal1 = "_addUser_userLanguagesVal2094714988";
        _addUser_userLanguages.add(_addUser_userLanguagesVal1);
        _addUser_user.getLanguages().addAll(_addUser_userLanguages);
        _addUser_user.setLastName("LastName1463934225");
        _addUser_user.setLookingForJob(true);
        _addUser_user.setPhoneNumber("PhoneNumber40616755");
        _addUser_user.setProfessionalSummary("ProfessionalSummary-278424884");
        java.util.List<java.lang.String> _addUser_userSkills = new java.util.ArrayList<java.lang.String>();
        java.lang.String _addUser_userSkillsVal1 = "_addUser_userSkillsVal1951653774";
        _addUser_userSkills.add(_addUser_userSkillsVal1);
        _addUser_user.getSkills().addAll(_addUser_userSkills);
        jobs.ws.client.User _addUser__return = port.addUser(_addUser_user);
        System.out.println("addUser.result=" + _addUser__return);


        }
        {
        System.out.println("Invoking getUser...");
        int _getUser_id = 1939504954;
        jobs.ws.client.User _getUser__return = port.getUser(_getUser_id);
        System.out.println("getUser.result=" + _getUser__return);


        }
        {
        System.out.println("Invoking deleteUser...");
        int _deleteUser_id = 779698820;
        boolean _deleteUser__return = port.deleteUser(_deleteUser_id);
        System.out.println("deleteUser.result=" + _deleteUser__return);


        }
        {
        System.out.println("Invoking updateUser...");
        int _updateUser_id = 1134540210;
        jobs.ws.client.User _updateUser_user = new jobs.ws.client.User();
        _updateUser_user.setAddress("Address-1948222155");
        _updateUser_user.setAge(748353491);
        java.util.List<java.lang.String> _updateUser_userCertifications = new java.util.ArrayList<java.lang.String>();
        java.lang.String _updateUser_userCertificationsVal1 = "_updateUser_userCertificationsVal-420957902";
        _updateUser_userCertifications.add(_updateUser_userCertificationsVal1);
        _updateUser_user.getCertifications().addAll(_updateUser_userCertifications);
        _updateUser_user.setEducationLevel("EducationLevel-1176855086");
        _updateUser_user.setEmail("Email-630701085");
        _updateUser_user.setFirstName("FirstName-1125772490");
        _updateUser_user.setId(-1292874694);
        java.util.List<java.lang.String> _updateUser_userLanguages = new java.util.ArrayList<java.lang.String>();
        java.lang.String _updateUser_userLanguagesVal1 = "_updateUser_userLanguagesVal572157462";
        _updateUser_userLanguages.add(_updateUser_userLanguagesVal1);
        _updateUser_user.getLanguages().addAll(_updateUser_userLanguages);
        _updateUser_user.setLastName("LastName-174484065");
        _updateUser_user.setLookingForJob(true);
        _updateUser_user.setPhoneNumber("PhoneNumber628363582");
        _updateUser_user.setProfessionalSummary("ProfessionalSummary1697951153");
        java.util.List<java.lang.String> _updateUser_userSkills = new java.util.ArrayList<java.lang.String>();
        java.lang.String _updateUser_userSkillsVal1 = "_updateUser_userSkillsVal709187360";
        _updateUser_userSkills.add(_updateUser_userSkillsVal1);
        _updateUser_user.getSkills().addAll(_updateUser_userSkills);
        jobs.ws.client.User _updateUser__return = port.updateUser(_updateUser_id, _updateUser_user);
        System.out.println("updateUser.result=" + _updateUser__return);


        }

        System.exit(0);
    }

}
