package jobs.management.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-12T01:48:18.377+02:00
 * Generated source version: 3.5.7
 *
 */
@WebServiceClient(name = "UserManagementImplService",
                  wsdlLocation = "file:/Users/abdelnassertine/git/repository/jobs.management.soap/src/main/webapp/wsdl/usermanagementimpl.wsdl",
                  targetNamespace = "http://www.jobs.management.soap/service")
public class UserManagementImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.jobs.management.soap/service", "UserManagementImplService");
    public final static QName UserManagementImplPort = new QName("http://www.jobs.management.soap/service", "UserManagementImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/abdelnassertine/git/repository/jobs.management.soap/src/main/webapp/wsdl/usermanagementimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserManagementImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/abdelnassertine/git/repository/jobs.management.soap/src/main/webapp/wsdl/usermanagementimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserManagementImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserManagementImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagementImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserManagementImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserManagementImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserManagementImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserManagementImpl
     */
    @WebEndpoint(name = "UserManagementImplPort")
    public UserManagementImpl getUserManagementImplPort() {
        return super.getPort(UserManagementImplPort, UserManagementImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagementImpl
     */
    @WebEndpoint(name = "UserManagementImplPort")
    public UserManagementImpl getUserManagementImplPort(WebServiceFeature... features) {
        return super.getPort(UserManagementImplPort, UserManagementImpl.class, features);
    }

}
