
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package jobs.management.soap.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-12T01:48:18.369+02:00
 * Generated source version: 3.5.7
 *
 */

@javax.jws.WebService(
                      serviceName = "UserManagementImplService",
                      portName = "UserManagementImplPort",
                      targetNamespace = "http://www.jobs.management.soap/service",
                      wsdlLocation = "file:/Users/abdelnassertine/git/repository/jobs.management.soap/src/main/webapp/wsdl/usermanagementimpl.wsdl",
                      endpointInterface = "jobs.management.soap.client.UserManagementImpl")

public class UserManagementImplPortImpl implements UserManagementImpl {

    private static final Logger LOG = Logger.getLogger(UserManagementImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see jobs.management.soap.client.UserManagementImpl#updateUser(int id, jobs.management.soap.client.User user)*
     */
    public jobs.management.soap.client.User updateUser(int id, jobs.management.soap.client.User user) {
        LOG.info("Executing operation updateUser");
        System.out.println(id);
        System.out.println(user);
        try {
            jobs.management.soap.client.User _return = new jobs.management.soap.client.User();
            _return.setAddress("Address-1771186433");
            _return.setAge(-424233254);
            _return.setEducationLevel("EducationLevel-113300361");
            _return.setEmail("Email-1395050539");
            _return.setFirstName("FirstName-1980368062");
            _return.setId(857632507);
            _return.setLastName("LastName1122756078");
            _return.setLocation("Location-941243074");
            _return.setPhoneNumber("PhoneNumber-894540539");
            _return.setProfessionalSummary("ProfessionalSummary810498497");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jobs.management.soap.client.UserManagementImpl#deleteUser(int id)*
     */
    public boolean deleteUser(int id) {
        LOG.info("Executing operation deleteUser");
        System.out.println(id);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jobs.management.soap.client.UserManagementImpl#getUser(int id)*
     */
    public jobs.management.soap.client.User getUser(int id) {
        LOG.info("Executing operation getUser");
        System.out.println(id);
        try {
            jobs.management.soap.client.User _return = new jobs.management.soap.client.User();
            _return.setAddress("Address-1115438694");
            _return.setAge(-265432499);
            _return.setEducationLevel("EducationLevel-1667356444");
            _return.setEmail("Email1436924839");
            _return.setFirstName("FirstName-371841010");
            _return.setId(276140087);
            _return.setLastName("LastName423435908");
            _return.setLocation("Location1692249822");
            _return.setPhoneNumber("PhoneNumber1628269613");
            _return.setProfessionalSummary("ProfessionalSummary1483935017");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jobs.management.soap.client.UserManagementImpl#addUser(jobs.management.soap.client.User user)*
     */
    public jobs.management.soap.client.User addUser(jobs.management.soap.client.User user) {
        LOG.info("Executing operation addUser");
        System.out.println(user);
        try {
            jobs.management.soap.client.User _return = new jobs.management.soap.client.User();
            _return.setAddress("Address1655752010");
            _return.setAge(-1350923603);
            _return.setEducationLevel("EducationLevel284928190");
            _return.setEmail("Email-1899242933");
            _return.setFirstName("FirstName971728589");
            _return.setId(520869986);
            _return.setLastName("LastName519468739");
            _return.setLocation("Location-1545351115");
            _return.setPhoneNumber("PhoneNumber701776950");
            _return.setProfessionalSummary("ProfessionalSummary-13701105");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
